###########################################################################
# Compile
###########################################################################
ARG VERSION=1.16.3 

FROM golang:${VERSION}-alpine As build

ENV GO111MODULE=on

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

ADD . /
WORKDIR /

RUN go mod download

RUN go build -o /main

###########################################################################
# Run
###########################################################################
FROM alpine:latest

ARG PORT=8080

EXPOSE ${PORT}

WORKDIR /
COPY --from=build /main /

CMD ["/main"]
