version: '3.4'

services:
  php:
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_XDEBUG=${PHP_INSTALL_XDEBUG}
        - INSTALL_REDIS=${PHP_INSTALL_REDIS}
        - INSTALL_MONGODB=${PHP_INSTALL_MONGODB}
        - INSTALL_MEMCACHED=${PHP_INSTALL_MEMCACHED}
        - INSTALL_OPCACHE=${PHP_INSTALL_OPCACHE}
        - INSTALL_MYSQLI=${PHP_INSTALL_MYSQLI}
        - INSTALL_IMAGE_OPTIMIZERS=${PHP_INSTALL_IMAGE_OPTIMIZERS}
        
    volumes: 
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
    
    expose:
      - 9000
  
  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        
    volumes:
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${APP_HOST}:/var/www

    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"

    depends_on:
        - php