version: '3.4'

services:

### php ##################################
  php:
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_XDEBUG=${PHP_INSTALL_XDEBUG}
        - INSTALL_REDIS=${PHP_INSTALL_REDIS}
        - INSTALL_MONGODB=${PHP_INSTALL_MONGODB}
        - INSTALL_MEMCACHED=${PHP_INSTALL_MEMCACHED}
        - INSTALL_OPCACHE=${PHP_INSTALL_OPCACHE}
        - INSTALL_MYSQLI=${PHP_INSTALL_MYSQLI}
        - INSTALL_IMAGE_OPTIMIZERS=${PHP_INSTALL_IMAGE_OPTIMIZERS}
    volumes: 
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ${APP_HOST}:/var/www
      - ${PHP_HOST_LOG_PATH}:/var/log/php

    expose:
      - 9000

    depends_on:
      - nginx
      - mysql
      - redis

### golang ##################################
  golang:
    build:
      context: ./golang
      args:
        - VERSION=${GOLANG_VERSION}
        
    volumes:
      - ${APP_HOST}:/var/www

### python ##################################
  python:
    build:
      context: ./python
      args:
        - VERSION=${PYTHON_VERSION}

    command: sleep infinity

    volumes:
      - ${APP_HOST}:/var/www

### nginx ##################################
  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        
    volumes:
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${APP_HOST}:/var/www

    ports:
      - ${PHP_HOST_PORT}:80

### mysql ##################################
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}

    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}

    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      
    ports:
      - ${MYSQL_PORT}:3306

### postgres ##################################
  postgres:
    image: postgres:${POSTGRES_VERSION}-alpine
   
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgres
      
    ports:
      - ${POSTGRES_PORT}:5432

### phpmyadmin ##################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin

    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
      - MAX_EXECUTION_TIME=${PMA_MAX_EXECUTION_TIME}
      - MEMORY_LIMIT=${PMA_MEMORY_LIMIT}
      - UPLOAD_LIMIT=${PMA_UPLOAD_LIMIT}

    ports:
      - ${PMA_PORT}:80

    depends_on:
      - php
      - mysql

### redis ################################################
  redis:
    build: ./redis

    volumes:
      - ${DATA_PATH_HOST}/redis:/data

    ports:
      - ${REDIS_PORT}:6379

### redis-webui ################################################
  redis-webui:
    image: erikdubbelboer/phpredisadmin

    environment:
      - ADMIN_USER=${REDIS_WEBUI_USERNAME}
      - ADMIN_PASS=${REDIS_WEBUI_PASSWORD}
      - REDIS_1_HOST=${REDIS_WEBUI_CONNECT_HOST}
      - REDIS_1_PORT=${REDIS_WEBUI_CONNECT_PORT}

    ports:
      - ${REDIS_WEBUI_PORT}:80

    depends_on:
      - redis
